// import axios from 'axios';

export default async function postSignUp(
  data: string
): Promise<ResponseSignUpProps> {
  const res = await fetch("https://mock-api.arikmpt.com/api/user/register", {
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: data,
    method: "POST",
  });
  const response = res.json() as unknown;
  return response as ResponseSignUpProps;
}
// Generated by https://quicktype.io

export interface ResponseSignUpProps {
  data: Data;
}

export interface Data {
  id: string;
  name: string;
  email: string;
  password: string;
  updated_at: string;
  created_at: string;
}
