export default async function GetCategory(id: string) {
  const Request = await fetch(
    "https://mock-api.arikmpt.com/api/category/" + id,
    {
      method: "GET",
      headers: {
        Accept: "application/json",
        Authorization: "Bearer" + localStorage.getItem("token"),
      },
    }
  );
  const response = (await Request.json()) as unknown;

  return response as ResponseGetCategoryProps;
}
// Generated by https://quicktype.io

export interface ResponseGetCategoryProps {
  data: Data;
}

export interface Data {
  id: string;
  is_active: boolean;
  name: string;
  updated_at: string;
  created_at: string;
}
