export default async function CreateCategory(data: string) {
  const Request = await fetch(
    "https://mock-api.arikmpt.com/api/category/create",
    {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: "Bearer" + localStorage.getItem("token"),
      },
      body: data,
    }
  );
  const response = (await Request.json()) as unknown;

  return response as ResponseCreateCategoryProps;
}
// Generated by https://quicktype.io

export interface ResponseCreateCategoryProps {
  data: Data;
}

export interface Data {
  id: string;
  is_active: boolean;
  name: string;
  updated_at: string;
  created_at: string;
}
