export default async function postLogIn(
  params: string
): Promise<ResponseLogInProps> {
  const res = await fetch("https://mock-api.arikmpt.com/api/user/login", {
    body: params,
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    method: "POST",
  });
  const response = (await res.json()) as unknown;

  return response as ResponseLogInProps;
}
// Generated by https://quicktype.io

export interface ResponseLogInProps {
  data: Data;
}

export interface Data {
  token: string;
}
